install vlc if not installed

diff --git a/gui b/gui
--- a/gui
+++ b/gui
@@ -23,7 +23,9 @@ check() {
     fi
   fi
   
-  
+  if ! command -v vlc &>/dev/null ;then
+	sudo pacman -S --noconfirm vlc || error "Failed to install VLC!"
+  fi
   
   #VLC youtube.lua
   if [ ! -f ~/.local/share/vlc/lua/playlist/youtube.lua ] || [ "$(sha256sum ~/.local/share/vlc/lua/playlist/youtube.lua | awk '{print $1}')" != "$(wget -qO- https://raw.githubusercontent.com/videolan/vlc/master/share/lua/playlist/youtube.lua | sha256sum | awk '{print $1}')" ];then
